import uuid
from datetime import datetime
from typing import Annotated, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, field_validator

from app.catalog.schemas import MAX_SALE_PRICE
from app.schema_types import MAX_LINES, DbId, Note, Qty, Reason, check_not_in_future

SaleStatus = Literal["posted", "cancelled"]
# Money in tiyn.
UnitPrice = Annotated[int, Field(strict=True, ge=0, le=MAX_SALE_PRICE)]


class SaleLineIn(BaseModel):
    model_config = ConfigDict(extra="forbid")

    product_id: DbId
    qty: Qty
    # None: take the product's sale_price.
    unit_price: UnitPrice | None = None


class SaleCreate(BaseModel):
    model_config = ConfigDict(extra="forbid")

    # Generated by the client once per sale form: a resent request returns the same sale.
    request_id: uuid.UUID
    customer_id: DbId | None = None
    sold_at: AwareDatetime | None = None
    note: Note = None
    lines: list[SaleLineIn] = Field(min_length=1, max_length=MAX_LINES)

    @field_validator("sold_at")
    @classmethod
    def _not_in_future(cls, value: datetime | None) -> datetime | None:
        return check_not_in_future(value, "Дата продажи не может быть в будущем")


class SaleCancel(BaseModel):
    model_config = ConfigDict(extra="forbid")

    reason: Reason


class SaleCustomerOut(BaseModel):
    id: int
    name: str
    phone: str | None


class SaleLineOut(BaseModel):
    product_id: int
    article: str
    name: str
    unit: str
    qty: int
    unit_price: int
    line_total: int


class SaleOut(BaseModel):
    id: int
    number: int
    request_id: uuid.UUID
    sold_at: datetime
    customer: SaleCustomerOut | None
    note: str | None
    status: SaleStatus
    cancelled_at: datetime | None
    cancel_reason: str | None
    created_by_name: str
    created_at: datetime
    lines: list[SaleLineOut]
    total: int


class SaleListItem(BaseModel):
    id: int
    number: int
    sold_at: datetime
    customer_name: str | None
    status: SaleStatus
    lines_count: int
    total_qty: int
    total: int


class SalePage(BaseModel):
    items: list[SaleListItem]
    total: int
    # Sum of total over posted sales matching the filter (all pages).
    sum_posted: int
