/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Products */
        get: operations["search_products_api_products_get"];
        put?: never;
        /** Create Product */
        post: operations["create_product_api_products_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Product */
        get: operations["get_product_api_products__product_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Product */
        patch: operations["update_product_api_products__product_id__patch"];
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Customers */
        get: operations["search_customers_api_customers_get"];
        put?: never;
        /** Create Customer */
        post: operations["create_customer_api_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer */
        get: operations["get_customer_api_customers__customer_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Customer */
        patch: operations["update_customer_api_customers__customer_id__patch"];
        trace?: never;
    };
    "/api/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Receipts */
        get: operations["list_receipts_api_receipts_get"];
        put?: never;
        /** Post Receipt */
        post: operations["post_receipt_api_receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipts/{receipt_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Receipt */
        get: operations["get_receipt_api_receipts__receipt_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/receipts/{receipt_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Receipt */
        post: operations["cancel_receipt_api_receipts__receipt_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sales */
        get: operations["list_sales_api_sales_get"];
        put?: never;
        /** Post Sale */
        post: operations["post_sale_api_sales_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/{sale_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sale */
        get: operations["get_sale_api_sales__sale_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sales/{sale_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Sale */
        post: operations["cancel_sale_api_sales__sale_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stock/adjustments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Adjustment */
        post: operations["create_adjustment_api_stock_adjustments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/products/{product_id}/movements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Movements */
        get: operations["list_movements_api_products__product_id__movements_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdjustmentCreate */
        AdjustmentCreate: {
            /** Product Id */
            product_id: number;
            /** Qty */
            qty: number;
            /** Reason */
            reason: string;
        };
        /** AdjustmentOut */
        AdjustmentOut: {
            movement: components["schemas"]["MovementOut"];
            /** Stock */
            stock: number;
        };
        /** CustomerCreate */
        CustomerCreate: {
            /** Name */
            name: string;
            /** Phone */
            phone?: string | null;
            /** Note */
            note?: string | null;
        };
        /** CustomerOut */
        CustomerOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
            /** Note */
            note: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** CustomerPage */
        CustomerPage: {
            /** Items */
            items: components["schemas"]["CustomerOut"][];
            /** Total */
            total: number;
        };
        /** CustomerUpdate */
        CustomerUpdate: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Note */
            note?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginIn */
        LoginIn: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** MovementOut */
        MovementOut: {
            /** Id */
            id: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Qty */
            qty: number;
            /** Kind */
            kind: string;
            /** Doc Type */
            doc_type: string | null;
            /** Doc Id */
            doc_id: number | null;
            /** Doc Number */
            doc_number: number | null;
            /** Note */
            note: string | null;
            /** Created By Name */
            created_by_name: string;
            /** Balance After */
            balance_after: number;
        };
        /** MovementPage */
        MovementPage: {
            /** Items */
            items: components["schemas"]["MovementOut"][];
            /** Total */
            total: number;
        };
        /** ProductCreate */
        ProductCreate: {
            /** Article */
            article: string;
            /** Name */
            name: string;
            /** Brand */
            brand?: string | null;
            /**
             * Unit
             * @default шт
             */
            unit: string;
            /** Sale Price */
            sale_price: number;
            /** Note */
            note?: string | null;
        };
        /** ProductOut */
        ProductOut: {
            /** Id */
            id: number;
            /** Article */
            article: string;
            /** Article Norm */
            article_norm: string;
            /** Brand */
            brand: string | null;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Sale Price */
            sale_price: number;
            /** Note */
            note: string | null;
            /** Is Archived */
            is_archived: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Stock */
            stock: number;
        };
        /** ProductPage */
        ProductPage: {
            /** Items */
            items: components["schemas"]["ProductOut"][];
            /** Total */
            total: number;
        };
        /** ProductUpdate */
        ProductUpdate: {
            /** Article */
            article?: string | null;
            /** Name */
            name?: string | null;
            /** Brand */
            brand?: string | null;
            /** Unit */
            unit?: string | null;
            /** Sale Price */
            sale_price?: number | null;
            /** Note */
            note?: string | null;
            /** Is Archived */
            is_archived?: boolean | null;
        };
        /** ReceiptCancel */
        ReceiptCancel: {
            /** Reason */
            reason: string;
        };
        /** ReceiptCreate */
        ReceiptCreate: {
            /** Lines */
            lines: components["schemas"]["ReceiptLineIn"][];
            /** Supplier */
            supplier?: string | null;
            /** Note */
            note?: string | null;
            /** Received At */
            received_at?: string | null;
        };
        /** ReceiptLineIn */
        ReceiptLineIn: {
            /** Product Id */
            product_id: number;
            /** Qty */
            qty: number;
            /** Unit Cost */
            unit_cost?: number | null;
        };
        /** ReceiptLineOut */
        ReceiptLineOut: {
            /** Product Id */
            product_id: number;
            /** Article */
            article: string;
            /** Name */
            name: string;
            /** Qty */
            qty: number;
            /** Unit Cost */
            unit_cost: number | null;
        };
        /** ReceiptListItem */
        ReceiptListItem: {
            /** Id */
            id: number;
            /** Number */
            number: number;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Supplier */
            supplier: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "posted" | "cancelled";
            /** Lines Count */
            lines_count: number;
            /** Total Qty */
            total_qty: number;
            /** Total Cost */
            total_cost: number | null;
        };
        /** ReceiptOut */
        ReceiptOut: {
            /** Id */
            id: number;
            /** Number */
            number: number;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Supplier */
            supplier: string | null;
            /** Note */
            note: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "posted" | "cancelled";
            /** Cancelled At */
            cancelled_at: string | null;
            /** Cancel Reason */
            cancel_reason: string | null;
            /** Created By Name */
            created_by_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Lines */
            lines: components["schemas"]["ReceiptLineOut"][];
            /** Total Qty */
            total_qty: number;
            /** Total Cost */
            total_cost: number | null;
        };
        /** ReceiptPage */
        ReceiptPage: {
            /** Items */
            items: components["schemas"]["ReceiptListItem"][];
            /** Total */
            total: number;
        };
        /** SaleCancel */
        SaleCancel: {
            /** Reason */
            reason: string;
        };
        /** SaleCreate */
        SaleCreate: {
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /** Customer Id */
            customer_id?: number | null;
            /** Sold At */
            sold_at?: string | null;
            /** Note */
            note?: string | null;
            /** Lines */
            lines: components["schemas"]["SaleLineIn"][];
        };
        /** SaleCustomerOut */
        SaleCustomerOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Phone */
            phone: string | null;
        };
        /** SaleLineIn */
        SaleLineIn: {
            /** Product Id */
            product_id: number;
            /** Qty */
            qty: number;
            /** Unit Price */
            unit_price?: number | null;
        };
        /** SaleLineOut */
        SaleLineOut: {
            /** Product Id */
            product_id: number;
            /** Article */
            article: string;
            /** Name */
            name: string;
            /** Unit */
            unit: string;
            /** Qty */
            qty: number;
            /** Unit Price */
            unit_price: number;
            /** Line Total */
            line_total: number;
        };
        /** SaleListItem */
        SaleListItem: {
            /** Id */
            id: number;
            /** Number */
            number: number;
            /**
             * Sold At
             * Format: date-time
             */
            sold_at: string;
            /** Customer Name */
            customer_name: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "posted" | "cancelled";
            /** Lines Count */
            lines_count: number;
            /** Total Qty */
            total_qty: number;
            /** Total */
            total: number;
        };
        /** SaleOut */
        SaleOut: {
            /** Id */
            id: number;
            /** Number */
            number: number;
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
            /**
             * Sold At
             * Format: date-time
             */
            sold_at: string;
            customer: components["schemas"]["SaleCustomerOut"] | null;
            /** Note */
            note: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "posted" | "cancelled";
            /** Cancelled At */
            cancelled_at: string | null;
            /** Cancel Reason */
            cancel_reason: string | null;
            /** Created By Name */
            created_by_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Lines */
            lines: components["schemas"]["SaleLineOut"][];
            /** Total */
            total: number;
        };
        /** SalePage */
        SalePage: {
            /** Items */
            items: components["schemas"]["SaleListItem"][];
            /** Total */
            total: number;
            /** Sum Posted */
            sum_posted: number;
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /** Username */
            username: string;
            /** Full Name */
            full_name: string;
            /** Role */
            role: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    login_api_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_api_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    search_products_api_products_get: {
        parameters: {
            query?: {
                q?: string | null;
                include_archived?: boolean;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_product_api_products_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_product_api_products__product_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_product_api_products__product_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProductUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProductOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_customers_api_customers_get: {
        parameters: {
            query?: {
                q?: string | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_customer_api_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_api_customers__customer_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_customer_api_customers__customer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_receipts_api_receipts_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                status?: ("posted" | "cancelled") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_receipt_api_receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_receipt_api_receipts__receipt_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_receipt_api_receipts__receipt_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                receipt_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReceiptCancel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReceiptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sales_api_sales_get: {
        parameters: {
            query?: {
                date_from?: string | null;
                date_to?: string | null;
                customer_id?: number | null;
                status?: ("posted" | "cancelled") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SalePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_sale_api_sales_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCreate"];
            };
        };
        responses: {
            /** @description Продажа с этим request_id уже проведена, возвращена она же */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"];
                };
            };
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sale_api_sales__sale_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_sale_api_sales__sale_id__cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sale_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaleCancel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SaleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_adjustment_api_stock_adjustments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdjustmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdjustmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_movements_api_products__product_id__movements_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path: {
                product_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MovementPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
